version: "3.5"
services:
  hasura-postgresql:
    hostname: postgresql
    container_name: hasura-postgresql
    environment:
      POSTGRES_PASSWORD: abcd1234
      POSTGRES_USER: hasura
    image: postgres:12
    ports:
      - "5433:5432"
    command: postgres -c 'max_connections=2000'
  hasura-graphql-engine:
    container_name: hasura-graphql-engine
    hostname: graphql-engine
    image: hasura/graphql-engine:v2.12.1.cli-migrations-v3
    ports:
      - "8080:8080"
    depends_on:
      - hasura-postgresql
    restart: always
    volumes:
      - ./hasura/migrations:/hasura-migrations
      - ./hasura/metadata:/hasura-metadata
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://hasura:abcd1234@postgresql:5432/hasura
      PG_DATABASE_URL: postgres://hasura:abcd1234@postgresql:5432/hasura
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: abcd1234
      HASURA_GRAPHQL_DATABASE_URL: postgres://hasura:abcd1234@postgresql:5432/hasura
